### ISSUE TITLE
Error loading Supplier

### ISSUE THREAD

**Issue by alcb1310** [alcb1310/bca#36]
When user tries to open the supplier with ID='1720301884001', for some reason we are having a runtime exception.

```bash
2024/01/25 00:08:54 http: panic serving [::1]:43606: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1868 +0xb9
panic({0x9bffa0?, 0xfba070?})
        /usr/lib/go/src/runtime/panic.go:920 +0x270
bca-go-final/internal/server.(*Server).SuppliersEdit.EditSupplier.func1({0xb6e500?, 0xc0000ae7b0?}, {0xb67160?, 0xc0000c2000?})
        /home/andres/go/src/github.com/alcb1310/bca-go-final/internal/views/bca/settings/partials/editsupplier_templ.go:143 +0x655
github.com/a-h/templ.ComponentFunc.Render(0xe44ef595d29544aa?, {0xb6e500?, 0xc0000ae7b0?}, {0xb67160?, 0xc0000c2000?})
        /home/andres/go/pkg/mod/github.com/a-h/templ@v0.2.513/runtime.go:36 +0x37
bca-go-final/internal/server.(*Server).SuppliersEdit(0xc000120678, {0xb6ccc8, 0xc0000c2000}, 0xc0000b0400)
        /home/andres/go/src/github.com/alcb1310/bca-go-final/internal/server/supplier.go:58 +0x2d3
net/http.HandlerFunc.ServeHTTP(0x4e4db9546f2d6c6f?, {0xb6ccc8?, 0xc0000c2000?}, 0xc0001ba000?)
        /usr/lib/go/src/net/http/server.go:2136 +0x29
bca-go-final/internal/server.(*Server).authVerify-fm.(*Server).authVerify.func1({0xb6ccc8, 0xc0000c2000}, 0xc0000b0200)
        /home/andres/go/src/github.com/alcb1310/bca-go-final/internal/server/middleware.go:66 +0x276
net/http.HandlerFunc.ServeHTTP(0xc0000b0100?, {0xb6ccc8?, 0xc0000c2000?}, 0x7f9947522c98?)
        /usr/lib/go/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000166240, {0xb6ccc8, 0xc0000c2000}, 0xc0000b0000)
        /home/andres/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
net/http.serverHandler.ServeHTTP({0xc0000ae0c0?}, {0xb6ccc8?, 0xc0000c2000?}, 0x6?)
        /usr/lib/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0000b4000, {0xb6e500, 0xc00048eba0})
        /usr/lib/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
        /usr/lib/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by alcb1310** [comment]
This issue was solved with PR #37:
https://github.com/alcb1310/bca-go-final/pull/37
